name = "JuliaTutor"
uuid = "75827d1f-33a1-4120-bbaf-a4a04206c74a"
authors = ["caseykneale"]
version = "0.1.0"

[compat]
julia = "1.4"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
